name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Download dependencies
      run: |
        export CGO_ENABLED=0
        export GOARCH=amd64
        export GO111MODULE=on
        go mod download
    
    - name: Build linux
      run: |
        export GOOS=linux && \
        go build -v -installsuffix cgo -ldflags="-w -s" -o nmac-parse-api-linux-amd64 cmds/nmac-parse-api/main.go && \
        go build -v -installsuffix cgo -ldflags="-w -s" -o nmac-parse-page-linux-amd64 cmds/nmac-parse-page/main.go && \
        go build -v -installsuffix cgo -ldflags="-w -s" -o nmac-parse-all-linux-amd64 cmds/nmac-parse-all/main.go

    - name: Upload linux nmac-parse-api artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: linux
        path: nmac-parse-api-linux-amd64
    
    - name: Upload linux nmac-parse-page artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: linux
        path: nmac-parse-page-linux-amd64
    
    - name: Upload linux nmac-parse-all artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: linux
        path: nmac-parse-all-linux-amd64

    - name: Build darwin
      run: |
        export GOOS=darwin && \
        go build -v -installsuffix cgo -ldflags="-w -s" -o nmac-parse-api-darwin-amd64 cmds/nmac-parse-api/main.go && \
        go build -v -installsuffix cgo -ldflags="-w -s" -o nmac-parse-page-darwin-amd64 cmds/nmac-parse-page/main.go && \
        go build -v -installsuffix cgo -ldflags="-w -s" -o nmac-parse-all-darwin-amd64 cmds/nmac-parse-all/main.go

    - name: Upload darwin nmac-parse-api artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: darwin
        path: nmac-parse-api-darwin-amd64
    
    - name: Upload darwin nmac-parse-page artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: darwin
        path: nmac-parse-page-darwin-amd64
    
    - name: Upload darwin nmac-parse-all artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: darwin
        path: nmac-parse-all-darwin-amd64

